# Generated by Django 6.0.2 on 2026-02-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(help_text='Problem statement in Markdown format')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('constraints', models.TextField(blank=True, help_text='Problem constraints e.g. 1 <= n <= 10^5')),
                ('examples', models.TextField(blank=True, help_text='Example inputs and outputs')),
                ('hints', models.TextField(blank=True, help_text='Hints stored as JSON array')),
                ('template_python', models.TextField(default='class Solution:\n    def solve(self):\n        pass', help_text='Python starter code')),
                ('template_javascript', models.TextField(default='/**\n * @return {number}\n */\nvar solve = function() {\n    \n};', help_text='JavaScript starter code')),
                ('template_java', models.TextField(default='class Solution {\n    public void solve() {\n        \n    }\n}', help_text='Java starter code')),
                ('total_submissions', models.IntegerField(default=0)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=5, help_text='Points awarded for solving (auto-set by difficulty)')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether problem is visible to users')),
                ('is_daily', models.BooleanField(default=False, help_text='Currently selected as daily problem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag')),
                ('topics', models.ManyToManyField(blank=True, related_name='problems', to='problems.topic')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problems',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input as JSON e.g. [[2,7,11,15], 9]')),
                ('expected_output', models.TextField(help_text='Expected output as JSON e.g. [0,1]')),
                ('explanation', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public cases shown to users, hidden cases used for final validation')),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty'], name='problems_difficu_cbb392_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_slug_fa7e51_idx'),
        ),
    ]
