# Generated by Django 5.0.6 on 2026-04-04 20:27

import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Group description', max_length=500)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Group avatar/logo', null=True, upload_to='group_avatars/')),
                ('join_code', models.CharField(default=groups.models.generate_group_code, help_text='Code to join group', max_length=6, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='If False, requires join_code')),
                ('max_members', models.IntegerField(default=50, help_text='Maximum group members')),
                ('current_members', models.IntegerField(default=1, help_text='Current member count')),
                ('total_points', models.IntegerField(default=0, help_text='Combined points of all members')),
                ('total_problems_solved', models.IntegerField(default=0, help_text='Total unique problems solved by group')),
                ('contests_participated', models.IntegerField(default=0, help_text='Number of contests participated')),
                ('contests_won', models.IntegerField(default=0, help_text='Number of contests won')),
                ('global_rank', models.IntegerField(default=0, help_text='Rank among all groups')),
                ('is_active', models.BooleanField(default=True, help_text='Whether group is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='GroupContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_groups', models.IntegerField(default=2, help_text='Minimum groups required')),
                ('max_groups', models.IntegerField(default=10, help_text='Maximum groups allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Contest',
                'verbose_name_plural': 'Group Contests',
                'db_table': 'group_contests',
            },
        ),
        migrations.CreateModel(
            name='GroupContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, help_text='Combined score of all members')),
                ('problems_solved', models.IntegerField(default=0, help_text='Unique problems solved by group')),
                ('rank', models.IntegerField(default=0, help_text='Rank in this contest')),
                ('time_penalty', models.IntegerField(default=0, help_text='Average time penalty of members')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group_contest_participations',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_invitations',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('points_contributed', models.IntegerField(default=0, help_text='Points earned while in group')),
                ('problems_solved', models.IntegerField(default=0, help_text='Problems solved while in group')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'db_table': 'group_members',
                'ordering': ['-points_contributed'],
            },
        ),
    ]
