# Generated by Django 5.0.6 on 2026-04-04 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(help_text='Group creator/admin', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcontest',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contests', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='groupcontestparticipation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupcontestparticipation',
            name='group_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='groups.groupcontest'),
        ),
        migrations.AddField(
            model_name='groupcontest',
            name='participating_groups',
            field=models.ManyToManyField(related_name='contests', through='groups.GroupContestParticipation', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['join_code'], name='groups_join_co_51c76f_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['-total_points'], name='groups_total_p_604e33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcontestparticipation',
            unique_together={('group_contest', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='groupinvitation',
            unique_together={('group', 'invited_user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
