# Generated by Django 5.0.6 on 2026-04-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contest_type', models.CharField(choices=[('INDIVIDUAL', 'Individual Contest'), ('GROUP', 'Group/Team Contest')], default='INDIVIDUAL', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=120)),
                ('join_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('invite_link', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=1000)),
                ('min_participants', models.IntegerField(default=1)),
                ('problem_assignment_mode', models.CharField(choices=[('SAME_FOR_ALL', 'Same problems for everyone'), ('UNIQUE_RANDOM', 'Unique random problems per participant'), ('MANUAL', 'Manually selected problems')], default='SAME_FOR_ALL', max_length=20)),
                ('problems_count', models.IntegerField(default=5)),
                ('send_notifications', models.BooleanField(default=True)),
                ('notification_before_minutes', models.IntegerField(default=30)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, help_text="e.g., 'WEEKLY_SUNDAY', 'WEEKLY_SATURDAY', 'DAILY'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='CONTEST_STARTING', max_length=50)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('time_penalty', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-total_score', 'time_penalty'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0)),
                ('time_from_start', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
