# Generated by Django 6.0.2 on 2026-02-17 17:33

import contests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Contest title', max_length=200)),
                ('description', models.TextField(help_text='Contest description and rules')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('is_official', models.BooleanField(default=False, help_text='True for LeetCode official contests')),
                ('join_code', models.CharField(default=contests.models.generate_join_code, help_text='Unique code to join contest', max_length=8, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='If False, needs join_code to participate')),
                ('start_time', models.DateTimeField(help_text='Contest start time')),
                ('end_time', models.DateTimeField(help_text='Contest end time')),
                ('duration_minutes', models.IntegerField(help_text='Contest duration in minutes')),
                ('max_participants', models.IntegerField(default=1000, help_text='Maximum number of participants (0 = unlimited)')),
                ('min_participants', models.IntegerField(default=2, help_text='Minimum participants required to start')),
                ('total_participants', models.IntegerField(default=0, help_text='Number of registered participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this contest', on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'db_table': 'contests',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, help_text='Total points earned in contest')),
                ('problems_solved', models.IntegerField(default=0, help_text='Number of problems solved')),
                ('rank', models.IntegerField(default=0, help_text='Current rank in contest')),
                ('time_penalty', models.IntegerField(default=0, help_text='Total time in seconds (for ranking tiebreaker)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contest Participation',
                'verbose_name_plural': 'Contest Participations',
                'db_table': 'contest_participations',
                'ordering': ['-total_score', 'time_penalty'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in contest')),
                ('points', models.IntegerField(help_text='Points for solving this problem in contest')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_contests', to='problems.problem')),
            ],
            options={
                'db_table': 'contest_problems',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0, help_text='Points earned for this submission')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('contest_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contestproblem')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contestparticipation')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission', to='submissions.submission')),
            ],
            options={
                'db_table': 'contest_submissions',
                'ordering': ['-submission_time'],
            },
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['start_time', 'end_time'], name='contests_start_t_5c679f_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['is_official'], name='contests_is_offi_2e5fee_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['join_code'], name='contests_join_co_b96dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='contestparticipation',
            index=models.Index(fields=['contest', '-total_score'], name='contest_par_contest_d58ea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipation',
            unique_together={('contest', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'problem')},
        ),
    ]
