# Generated by Django 6.0.2 on 2026-02-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text="User's submitted code")),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILE_ERROR', 'Compile Error')], default='PENDING', max_length=30)),
                ('runtime', models.IntegerField(blank=True, help_text='Execution time in ms', null=True)),
                ('memory', models.FloatField(blank=True, help_text='Memory used in MB', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error output if failed')),
                ('test_results', models.TextField(blank=True, help_text='JSON: [{input, expected, actual, passed, time}]')),
                ('test_cases_passed', models.IntegerField(default=0)),
                ('test_cases_total', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0, help_text='Points earned for this submission')),
                ('is_first_accepted', models.BooleanField(default=False, help_text='True if this is the first accepted for this problem by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='submissions_user_id_34eafe_idx'), models.Index(fields=['status'], name='submissions_status_dcc854_idx'), models.Index(fields=['-created_at'], name='submissions_created_80fb8e_idx')],
            },
        ),
    ]
