# Generated by Django 5.0.6 on 2026-04-04 20:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, help_text='User biography', max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('problems_solved', models.IntegerField(default=0, help_text='Total unique problems solved')),
                ('easy_solved', models.IntegerField(default=0)),
                ('medium_solved', models.IntegerField(default=0)),
                ('hard_solved', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0, help_text='Total code submissions')),
                ('accepted_submissions', models.IntegerField(default=0, help_text='Successfully accepted submissions')),
                ('total_points', models.IntegerField(default=0, help_text='Total points earned (Easy:5, Medium:10, Hard:15)')),
                ('global_ranking', models.IntegerField(default=0, help_text='Global rank based on points')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days of solving problems')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest streak ever achieved')),
                ('last_activity_date', models.DateField(blank=True, help_text='Last day user solved a problem', null=True)),
                ('contests_participated', models.IntegerField(default=0, help_text='Number of contests participated in')),
                ('contests_won', models.IntegerField(default=0, help_text='Number of contests won (rank 1)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-total_points', '-problems_solved'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this daily problem', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_selections', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Daily Problem',
                'verbose_name_plural': 'Daily Problems',
                'db_table': 'daily_problems',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyProblemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('daily_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dailyproblem')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Problem Completion',
                'verbose_name_plural': 'Daily Problem Completions',
                'db_table': 'daily_problem_completions',
            },
        ),
        migrations.AddField(
            model_name='dailyproblem',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_daily_problems', through='users.DailyProblemCompletion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['total_points', '-problems_solved'], name='users_total_p_a34206_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['global_ranking'], name='users_global__8d429e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyproblemcompletion',
            unique_together={('user', 'daily_problem')},
        ),
    ]
