# Generated by Django 6.0.2 on 2026-02-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        ('users', '0002_alter_user_options_user_github_username_user_ranking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this daily problem', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Problem',
                'verbose_name_plural': 'Daily Problems',
                'db_table': 'daily_problems',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyProblemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Problem Completion',
                'verbose_name_plural': 'Daily Problem Completions',
                'db_table': 'daily_problem_completions',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-total_points', '-problems_solved'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='ranking',
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_submissions',
            field=models.IntegerField(default=0, help_text='Successfully accepted submissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='contests_participated',
            field=models.IntegerField(default=0, help_text='Number of contests participated in'),
        ),
        migrations.AddField(
            model_name='user',
            name='contests_won',
            field=models.IntegerField(default=0, help_text='Number of contests won (rank 1)'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days of solving problems'),
        ),
        migrations.AddField(
            model_name='user',
            name='global_ranking',
            field=models.IntegerField(default=0, help_text='Global rank based on points'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Last day user solved a problem', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest streak ever achieved'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points earned (Easy:5, Medium:10, Hard:15)'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_submissions',
            field=models.IntegerField(default=0, help_text='Total code submissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='problems_solved',
            field=models.IntegerField(default=0, help_text='Total unique problems solved'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['total_points', '-problems_solved'], name='users_total_p_a34206_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['global_ranking'], name='users_global__8d429e_idx'),
        ),
        migrations.AddField(
            model_name='dailyproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_selections', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='dailyproblemcompletion',
            name='daily_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dailyproblem'),
        ),
        migrations.AddField(
            model_name='dailyproblemcompletion',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='dailyproblemcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyproblem',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_daily_problems', through='users.DailyProblemCompletion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyproblemcompletion',
            unique_together={('user', 'daily_problem')},
        ),
    ]
